### ISSUE TITLE
Fix compiler warnings in debug mode 

### ISSUE THREAD

**Issue by dylanbmorgan** [dylanbmorgan/efield-sim#7]
On line 48 & 49 of particle_mover.f90, gfortran complains that there is a possible change in value from real to integer. Seems a bit weird as the whole point of the `floor()` intrinsic function is to do exactly that

**Comment by ShufflerBardOnTheEdge** [comment]
This was because you were adding 1.0_dp to the result of the floor. You were trying to store an integer plus a real as an integer. I have changed 1.0_dp to 1 which fixed the issue.
